@baseUrl = http://localhost:3000
@itemId = 558f3c78-8666-46a1-b262-968a09e36a56

GET {{baseUrl}}/schedules?date=2024-05-01

###

POST {{baseUrl}}/schedules
Content-Type: application/json

{    
  "client": "Clodoaldo Dantas",
  "date": "2024-04-30",
  "time": "08:00"
}

###

DELETE {{baseUrl}}/schedules/{{itemId}}