@baseUrl = http://localhost:3000

GET {{baseUrl}}/schedules?date=2024-04-30

###

POST {{baseUrl}}/schedules
Content-Type: application/json

{    
  "client": "Clodoaldo Dantas",
  "date": "2024-04-30",
  "time": "08:00"
}